// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFMp_qnZsPtH2EU5ayqB-NzCnkq6rAwyw',
    appId: '1:528863677064:web:3193da5af484a6fd62ed3d',
    messagingSenderId: '528863677064',
    projectId: 'flutterproject-5cc13',
    authDomain: 'flutterproject-5cc13.firebaseapp.com',
    storageBucket: 'flutterproject-5cc13.firebasestorage.app',
    measurementId: 'G-HX6E0HFQYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIPXILKZsBp9Ns2tpm-dI4Ch0-xWoFpis',
    appId: '1:528863677064:android:d8cca830ced85d1962ed3d',
    messagingSenderId: '528863677064',
    projectId: 'flutterproject-5cc13',
    storageBucket: 'flutterproject-5cc13.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB72znHgkRAv13T1IprJs-2PgXtR2E6HAw',
    appId: '1:528863677064:ios:9e3af2c1f8cc710362ed3d',
    messagingSenderId: '528863677064',
    projectId: 'flutterproject-5cc13',
    storageBucket: 'flutterproject-5cc13.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );
}
